apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8s
spec:
  selector:
    matchLabels:
      app: spring-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-k8s
    spec:
      containers:
        - name: spring-k8s
          image: anshgoyal7078848866/springbootapp
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
            
apiVersion: v1
kind: Service
metadata:
  name: spring-k8s-svc
spec:
  selector:
    app: spring-k8s
  ports:
    - protocol: "TCP"
      port: 8086
      targetPort: 8086
  type: NodePort            
            
